apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 100-master-silicom-registry
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W3JlZ2lzdHJpZXMuaW5zZWN1cmVdCnJlZ2lzdHJpZXMgPSBbJ2RvY2tlci5zaWxpY29tLmRrOjUwMDAnXQ==
        filesystem: root
        mode: 0420
        path: /etc/containers/registries.d/100-master-silicom-registry